### ISSUE TITLE
安装Tmux后无法运行

### ISSUE THREAD

**Issue by gsdgui** [hpc-admin-sist/DockerMonitor#40]
1. apt-get install tmux
然后运行 tmux 提示 tmux: error while loading shared libraries: libutempter.so.0: cannot open shared object file: No such file or directory
好像是缺少  libutempter.so.0 这个.so文件，不知道改如何解决

**Comment by ShenhanQian** [comment]
请提供您的用户名

**Comment by gsdgui** [comment]
主机10.15.89.41
UID: 1797
cs280-zenghao1
zenghao1@shanghaitech.edu.cn

**Comment by ShenhanQian** [comment]
账户的`libutempter0 `库文件损坏，用以下命令重装后恢复正常：
```
apt install libutempter0 --reinstall
```

已测试tmux可以正常启动。

**Comment by gsdgui** [comment]
嗯嗯，可以了，谢谢！
