### ISSUE TITLE
我在安装apt-get 安装时遇到了问题

### ISSUE THREAD

**Issue by 741272702** [hpc-admin-sist/DockerMonitor#41]
**问题描述**
我使用apt-get 安装就会报错
/var/lib/dpkg/info/emacsen-common.postinst: 40: /var/lib/dpkg/info/emacsen-common.postinst: /usr/lib/emacsen-common/emacs-package-install: not found
dpkg: 处理软件包 emacsen-common (--configure)时出错：
 子进程 已安装 post-installation 脚本 返回错误状态 127
在处理时有错误发生：
 emacsen-common

root@10.15.89.41 port: 22302
账号 ：zenghy
**尝试过的解决办法**
我昨天在使用apt install libgl1-mesa-glx 安装我所需要的包时，遇到了依赖的包版本不匹配的问题，于是我将依赖的包libglapi-mesa 使用 apt-get autoremove libglapi-mesa 命令进行卸载，想要重新安装，可是之后就一直报错：
![1607360062(1)](https://user-images.githubusercontent.com/39368947/101437804-f58e3480-394b-11eb-9d18-b01a27a155ae.png)

我在上网查寻解决办法，发现没有能够解决的，于是我按照报错的信息，使用groupadd 添加了组crontab，之后我再次使用apt-get 安装，依旧报错上面类似的错误，缺少组messagebus和mlocate，于是我又添加了这两个组；
![1607360183(1)](https://user-images.githubusercontent.com/39368947/101437817-fcb54280-394b-11eb-863d-6a4fba731717.png)
![1607360129(1)](https://user-images.githubusercontent.com/39368947/101437822-ff179c80-394b-11eb-99fd-1c47f3ded1ff.png)

之后就会报上述问题描述的错误；
![3878e86939b04de957cf322b68da55c](https://user-images.githubusercontent.com/39368947/101437882-1fdff200-394c-11eb-896a-933a5194b860.png)

但貌似包能够安装上去，于是我就没管上述的错误，又使用apt install libgl1-mesa-glx命令安装我最开始需要的包，
但是之后我运行我的代码又报错libXdamage.so.1: cannot open shared object file: No such file or directory，
于是我又安装这个包，但是发现这个包已经安装了，但仍会报错，所以我就又将这个包卸载重新安装了，
之后我运行我的代码报错ImportError: libdrm.so.2: cannot open shared object file: No such file or directory
但是我安装这个包时发现这个包也是已经安装了的

**可能引起这一问题的原因是什么？**
我在google查询时，看到我最开始的缺少组的错误，应该是因为卸载包时没有卸载干净导致的，但是后续的错误我就不太清楚了

**这一问题是否长期存在？**
昨天晚上刚刚出现的

****

**Comment by ShenhanQian** [comment]
我在你的账号下尝试了`apt install htop`，没有报错信息，说明apt是基本正常的。

**Comment by ShenhanQian** [comment]
在运行`apt update`之后运行`apt install libgl1-mesa-glx`，也顺利安装了，没有遇到问题。

**Comment by 741272702** [comment]
> 在运行`apt update`之后运行`apt install libgl1-mesa-glx`，也顺利安装了，没有遇到问题。
多谢了，我测试了一下，运行代码真的没有问题了！

**Comment by ShenhanQian** [comment]
不客气
