### ISSUE TITLE
CUDA更新后请求节点重启

### ISSUE THREAD

**Issue by shcotton** [hpc-admin-sist/DockerMonitor#42]
**需要重启特定节点还是全部节点？**
需要重启全部节点

**是否需要重置系统环境？**
`/p300`文件夹之外的数据会全部清空
无需重置

**账户信息**
caoyf，端口号 22898

**原因**
在运行Anaconda环境下的pytorch时，因提示CUDA版本过旧而无法利用GPU，因此尝试按其提示更新CUDA。此操作亦更新了NVIDIA驱动，更新后有提示信息要求重启。运行 `nvidia-smi` 发现报错 `Failed to initialize NVML: Driver/library version mismatch`，网上搜索结果亦称该问题重启即可解决。因此请求重启全部节点，但保留所有数据。

**Comment by ShenhanQian** [comment]
用户环境为Docker容器，无法对系统驱动进行修改，重启并不能解决问题。请卸载已经自行安装的驱动程序并安装与之匹配的PyTorch版本。

**Comment by shcotton** [comment]
> 用户环境为Docker容器，无法对系统驱动进行修改，重启并不能解决问题。请卸载已经自行安装的驱动程序并安装与之匹配的PyTorch版本。

请问可以重置节点吗……？卸载原先安装的驱动后，发现 `nvidia-smi` 直接消失了。尝试安装官方源 `nvidia-utils` 各版本，仍然存在上述 `version mismatch` 问题。感觉是当时安装新驱动时干扰了以前的配置，由于当前无法查询到以前的NVIDIA驱动版本，不知下一步应该如何修复。因此希望能够直接重置节点，有关数据已经备份。

**Comment by ShenhanQian** [comment]
在你卸载自行安装的驱动之后，我重启了你的计算节点，nvidia-smi已经恢复了

**Comment by shcotton** [comment]
> 在你卸载自行安装的驱动之后，我重启了你的计算节点，nvidia-smi已经恢复了

多谢调整，经测试GPU调用也已经恢复正常
