### ISSUE TITLE
Configuration about Gurobi Optimizer 

### ISSUE THREAD

**Issue by PeppaCat** [hpc-admin-sist/DockerMonitor#44]
**问题描述**
问题背景

数值优化课题需要使用gurobi优化器，优化器的许可（license）为academic use，可以由个人自由申请。但是，在docker中运行gurobi优化器需要在宿主机器中进行相应设置才能使用，否则会提示：
```
License is not valid in a Docker container, contact Gurobi support for more options
```
**问题针对于集群系统还是普适于Linux系统？**
是否有已知的问题解答？

宿主机器的设置在gurobi的文档中给出，希望管理员能帮忙配置一下
具体操作见如下文档：
在docker中使用gurobi：https://support.gurobi.com/hc/en-us/articles/360040044712
在cluster中使用gurobi: https://support.gurobi.com/hc/en-us/articles/360013195412
license获取：https://www.gurobi.com/academia/academic-program-and-licenses/

**集群文档是否有相关内容？**
集群文档是否涉及，是否存在错误，是否需要更新或补充？

可添加关于数值优化课题使用gurobi的描述

**Comment by ShenhanQian** [comment]
我已阅读Gurobi的配置文档，正在等待验证邮件。为了方便测试，请提供你的集群用户名。

**Comment by PeppaCat** [comment]
你好。

我的用户名应为cs280-wangjch2,登录端口为22870。
我今天下午还可以登录，但是现在已经登陆不上了，并且在ai cluster上我的用户记录也没有了。请问这是你们的操作吗？

谢谢

发件人: Qian Shenhan<mailto:notifications@github.com>
发送时间: 2020年12月17日 16:51
收件人: hpc-admin-sist/DockerMonitor<mailto:DockerMonitor@noreply.github.com>
抄送: 王嘉晨(2018级)<mailto:wangjch2@shanghaitech.edu.cn>; Author<mailto:author@noreply.github.com>
主题: Re: [hpc-admin-sist/DockerMonitor] Configuration about Gurobi Optimizer (#44)


我已阅读Gurobi的配置文档，正在等待验证邮件。为了方便测试，请提供你的集群用户名。

―

**Comment by PeppaCat** [comment]
谢谢。我已发送邮件给hpc-admin-sist。如果没有收到，我的用户名为cs280-wangjch2,。另外，现在该用户已经登陆不上了。

**Comment by ShenhanQian** [comment]
![image](https://user-images.githubusercontent.com/23174052/102480866-dace6500-409b-11eb-8036-a252a51b60f3.png)
根据端口号我查询到了这个账户，是`wangjch2-admin`而不是`cs280-wangjch2`。监控显示容器仍然在运行。

**Comment by ShenhanQian** [comment]
本集群是GPU集群，但根据官网的这个[帖子](https://support.gurobi.com/hc/en-us/articles/360012237852-Does-Gurobi-support-GPUs-)， Gurobi不是面向GPU的。

**Comment by PeppaCat** [comment]
谢谢回复。我现在可以重新登陆上了。
Gurobi能利用多核进行并行计算，加速求解过程。这是我希望能够在集群上使用的原因。请问管理员还计划提供gurobi的支持吗？

**Comment by ShenhanQian** [comment]
我们已经在admin节点上配置好了Gurobi，但是无法正常启动token server。

**Comment by PeppaCat** [comment]
好吧，明白了。谢谢管理员！我再想想别的办法吧。
