### ISSUE TITLE
About how to build a system like AI_Cluster.

### ISSUE THREAD

**Issue by Rejur** [hpc-admin-sist/DockerMonitor#45]
管理员好：

我想在实验室的几台服务器上构建出类似GPU集群一样的系统，但是我不太了解如何将容器中的/usr这类文件同步到宿主机上，能否告诉我核心如何实现多个节点同步安装好的环境的呢？

我的邮箱是hulin@shanghaitech.edu.cn.
如果不方便告知的话也没关系。
谢谢。

**Comment by ShenhanQian** [comment]
您好：

集群的多节点存储共享不是通过`文件同步`，而是通过`共用挂载盘`实现的。这种做法要求所有机器都通过网线挂载同一块存储盘，以下涉及的存储均在这块共用存储盘上进行。我们的做法包含`制作镜像`、`创建用户目录`、`新建用户容器`三个环节：

**制作镜像**
将一配置好的容器镜像`docker-image`的系统目录（包括`/bin`  `/etc`  `/lib`  `/lib64`  `/opt`  `/root`  `/sbin`  `/usr`  `/var`）拷贝出来作为模板目录`baseline`。

**创建用户目录**
新建用户`xiaoming`时，从`baseline`拷贝一个目录`<STORAGE_ROOT>/users/xiaoming`作为用户的个人文件夹。

**新建用户容器**
在每台集群机器上，为`xiaoming`创建一个容器`xiaoming-<hostname>`，并将上一步中新建的用户目录挂载到容器的系统路径下（这一步是实现多节点存储共享的关键，详见[集群系统源码](https://github.com/hpc-admin-sist/DockerMonitor/blob/c094a52d4fc0f37c35140308d6b18e065f39ad36/handler/base_handler.py#L62-L72)）。

当前的集群系统是历届SISTor智慧和汗水的结晶，有其巧妙之处也有其弊端。如您在实践过程中发现更加优雅、可靠的解决方案，敬请赐教！

**Comment by Rejur** [comment]
非常感谢您的回复，赐教不敢，还是交流。
