### ISSUE TITLE
MacOS连接服务器后自动断线

### ISSUE THREAD

**Issue by tonysy** [hpc-admin-sist/DockerMonitor#6]
如题
```
$ Connection to 10.19.124.11 closed by remote host.
Connection to 10.19.124.11 closed.
```

**Comment by tonysy** [comment]
Solution
检查shadowsocks 设置，切换成pac自动模式即可解决

**Comment by piaozhx** [comment]
open模式这样大家都能看到

**Comment by XiAom611** [comment]
也可以通过设置
/etc/ssh/ssh_config中
ServerAliveInterval 60 (表示每60秒向服务器发送一次,这样就保持长连接了)
ServerAliveCountMax 3 (表示服务器发出请求后客户端没有响应的次数达到一定值, 就自动断开. 正常情况下, 客户端不会不响应)
